# Sudo used for custom apt setup
sudo: true

env:
 - GHCVER=7.10.1 CABALVER=1.22
 - GHCVER=head CABALVER=head

# Allow for develop branch to break
matrix:
  allow_failures:
   - env: GHCVER=head CABALVER=head

# Manually install ghc and cabal
before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - export PATH=$HOME/.cabal/bin:$PATH
  - travis_retry cabal update

install:
  - echo $PATH
  - cabal --version
  - ghc --version
  - cabal install --verbose

script:
  - true
