# Use new container infrastructure to enable caching
sudo: false

language: haskell

ghc:
  - "7.10"

before_install:
  - ghc --version
  - cabal --version
  - travis_retry cabal update

install:
  - cabal install --only-dependencies --enable-tests

script:
  - true
