# Use new container infrastructure to enable caching
sudo: false

language: haskell

ghc:
  - 7.10
  - 8.1

before_install:
  - ghc --version
  - cabal --version
  - travis_retry cabal update

script:
  - cabal install
